updated yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -25,7 +25,7 @@ jobs:
       run: dotnet build --no-restore
 
     - name: Test
-      run: dotnet test --configuration Debug --logger "console;verbosity=diagnostic"
+      run: dotnet test reqnroll-bdd-automation/reqnroll-bdd-automation.csproj --configuration Debug --logger "console;verbosity=diagnostic"
 
 
 
@@ -47,8 +47,17 @@ jobs:
     - name: Move Allure results to expected directory
       if: always()
       run: |
-        mkdir -p ../allure-results
-        cp -r bin/Debug/net8.0/allure-results/* ../allure-results/ || echo "No files found"
+        mkdir -p allure-results
+        cp -r reqnroll-bdd-automation/bin/Debug/net8.0/allure-results/* allure-results/ || echo "No files found"
+
+
+
+    - name: Debug Allure results content
+      if: always()
+      run: |
+        echo "Checking allure-results files:"
+        ls -l reqnroll-bdd-automation/bin/Debug/net8.0/allure-results || echo "Not found"
+
 
     - name: Build Allure test report
       uses: simple-elf/allure-report-action@master
